### ISSUE TITLE
Problème de Pull Request

### ISSUE THREAD

**Issue by KylianeAubel** [jsboigeECE/2024-ECE-Ing4-Fin-Sudoku-Gr02#10]
Bonjour Monsieur,

Je ne parviens pas à pull request mon fichier pour le partager à la classe. Ils me disent qu'il me faut une autorisation pour PR. Savez vous comment faire ? 

Cordialement, Kyliane Aubel

**Comment by jsboigeECE** [comment]
Bonjour,
Normalement tu n'as pas besoin de permissions pour faire une PR vers ce dépôt ou depuis ce dépôt vers votre fork. Ceci dit, l'un des groupes a semble-t-il édité les paramètres de leur fork pour qu'on ne puisse pas faire une PR de l'extérieur. Mais ce n'est pas le cas sur ce dépôt ou j'ai reçu et fusionné déjà pas mal de PRs.

**Comment by AUBELKyliane** [comment]
Bonjour Monsieur,
Merci pour votre réponse. J'ai de réels difficultés à pull et push les fichiers. Je ne peux plus non plus avoir accés au solution explorer alors que je pouvais avoir, je ne peux plus donc compiler. C'est possible de tout recommencer ? 
Cordialement

**Comment by KylianeAubel** [comment]
Je viens de recloner dans un autre répertoire mais je n'ai toujours pas accès au solution explorer (il y a marqué open solution mais lorsque je clique dessus, rien ne se produit)

**Comment by jsboigeECE** [comment]
Si le so

> Je viens de recloner dans un autre répertoire mais je n'ai toujours pas accès au solution explorer (il y a marqué open solution mais lorsque je clique dessus, rien ne se produit)

si le solution explorer est manquant, il est peut-être masqué sur le côté, ou vous pouvez le rajouter à partir du menu principal s'il a été fermé lors d'une précédente session

**Comment by jsboigeECE** [comment]
Je ferme cette issue dont nous avons discuté dans votre PR
