### ISSUE TITLE
Probleme pour Commit

### ISSUE THREAD

**Issue by KylianeAubel** [jsboigeECE/2024-ECE-Ing4-Fin-Sudoku-Gr02#19]
Bonsoir Monsieur,

J'ai rencontré des problèmes à nouveau avec GitHub, j'ai recloné à nouveau le répertoire mais je ne pouvais pas commit. J'ai du effacé le fork pour en créer un nouveau. Normalement, je vous ai envoyé un Pull Request. Pouvez-vous confirmer ? De plus, pouvons nous toujours améliorer notre code d'ici les oraux ?
Cordialement

**Comment by jsboigeECE** [comment]
Je crois que tu as pu résoudre ton problème par la suite, je clos cette issue
