### ISSUE TITLE
CSPChocoSolver: Problème de récupération du code du fichier python du solver

### ISSUE THREAD

**Issue by DanyKuoy** [jsboigeECE/2024-ECE-Ing4-Fin-Sudoku-Gr02#5]
Bonjour monsieur,

Je n'arrive pas à comprendre pourquoi lorsque je récupère le script du fichier python, depuis le code c#, le code du solver de base (backtracking) arrive à s'exécuter quoi qu'il arrive, même lorsque je mets tout le code python en commentaire.

Mais en remplaçant, dans le fichier "CSPChocoSolver.cs", la ligne de code "string code = Resources.CSPChocoSolver_py;" par 
"string code = File.ReadAllText(@"C:\GitHub\2024-ECE-Ing4-Fin-Sudoku-Gr02\Sudoku.CSPChoco\Resources\CSPChocoSolver.py");", j'arrive à récupérer le script du fichier python modifié. 

Pouvez-vous m'aidez à corriger le problème svp ?

Cordialement,
KUOY Dany

**Comment by DanyKuoy** [comment]
Bonsoir monsieur,

J'ai finalement pu régler mon problème de récupération du code python.

Actuellement, on a un code python permettant de résoudre un sudoku avec programmation par contraintes en utilisant, comme indiqué sur le sujet, l'une des possibilités, à savoir avec la librairie PuLP. On utilise le solveur de base de la librairie PuLP, qui est CBC MILP. On voulait vous demander si le code respectait bien le sujet, car étant donné que Choco-Solver est une bibliothèque Java, on ne voit pas vraiment comment l'inclure avec PuLP.

**Comment by jsboigeECE** [comment]
> Bonsoir monsieur,
> 
> J'ai finalement pu régler mon problème de récupération du code python.
> 
> Actuellement, on a un code python permettant de résoudre un sudoku par CSP en utilisant, comme indiqué sur le sujet, l'une des possibilités, à savoir avec la librairie PuLP. On utilise le solveur de base de la librairie PuLP, qui est CBC. On voulait vous demander si le code respectait bien le sujet, car étant donné que Choco-Solver est une bibliothèque Java, on ne voit pas vraiment comment l'inclure avec PuLP.

Oui pas de souci pour utiliser Pulp avec le ou les solvers de votre choix. 
Pour ce qui est de chocosolver, vos camarades du groupe 1 sont partis pour l'intégrer via ikvm (bridge java/.net) mais vous êtes en Python et ne devriez avoir besoin que du bridge pythonnet. A priori dans Pulp il faut fournir le chemin du solver utilisé d'une façon ou d'une autre. Du coup, vous pouvez rajouter l'executable dans un répertoire de votre projet, définir dans VS dans les propriétés du fichier du solver qu'il doit être copié dans le répertoire de sortie, et vous pourrez dans votre code en désigner le chemin relatif.
Bref, faites moi une PR si vous avez du mal et je vous ferai les ajustements nécessaires

**Comment by jsboigeECE** [comment]
Je vois que vous avez fait une PR, du coup je ferme cette issue, et on pourra continuer dans vos PRs
