### ISSUE TITLE
Problème mise à jour code Pull

### ISSUE THREAD

**Issue by SofianeMob21** [jsboigeECE/2024-ECE-Ing4-Fin-Sudoku-Gr02#9]
Bonsoir,

J'ai cliqué directement sur Pull pour avoir les ajouts et corrections à travers Visual Studio Community, pourtant lorsque j’exécute le code, je n'ai pas l'affichage des autres solveurs (CSPChoco, Annealing) quand on est dans la partie Choose a solver.
Ducoup j'ai voulu re-cloner pour pouvoir à nouveau Commit et Push mais je ne peux pas Push. Mes camarades ne peuvent pas non plus Push (remote: Permission to jsboigeECE/2024-ECE-Ing4-Fin-Sudoku-Gr02.git denied to ryantlb.)

Cordialement, Sofiane

**Comment by jsboigeECE** [comment]
Bonjour, il vous faut travailler sur des clones du fork de votre groupe et non pas sur un clone de ce dépôt principal.
Les Pull request permettent ensuite de faire passer le code entre ce dépôt principal sur lequel vous n'avez effectivement pas les droits et votre fork. Quelle est l'url de votre fork?

**Comment by ryantlb** [comment]
Bonjour, merci pour votre réponse, c'est clair. L'url de notre fork est : https://github.com/SofianeMob21/2024-ECE-Ing4-Fin-Sudoku-Gr02.git. Sofiane nous y a ajouté en tant que collaborateurs donc ça devrait être bon.

**Comment by jsboigeECE** [comment]
Parfait, du coup je ferme cette issue
